-- Workspaces 1-2 on DP-3 (primary), 3-4 on HDMI-A-1 (secondary)
hl.workspace_rule({ workspace = "1", monitor = "DP-3",     default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "DP-3",                     persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "HDMI-A-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "HDMI-A-1",                 persistent = true })
